/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SubmitContent': ApiRouteHandler<{ url: string; to: string; purpose: string }, ApiResponse<200, { message: string; requestId: string }> | ApiResponse<500, { error: string }>, { topic: 'content.requested'; data: { url: string; to: string; purpose: string } }>
    'ProcessContent': EventHandler<{ url: string; to: string; purpose: string }, never>
  }
    
}